[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.114.0"
HUGO_THEME = "hugo-scroll"

[context.production]
command = "hugo --gc -b ${URL}"
[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "hugo --gc -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
command = "hugo --gc -b ${DEPLOY_PRIME_URL}"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"
[plugins.inputs]
debug = true
srcdir = ""
